steps:
# Install CovidInfo dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Install Function dependencies
- name: 'gcr.io/cloud-builders/functions/npm'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '--prod']
# Deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']