steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', 'firebase', 'use', '--add']
# Deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']