steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '--prod']
  env: [
    'VUE_APP_FIREBASE_API_KEY=${_VUE_APP_FIREBASE_API_KEY}',
    'VUE_APP_FIREBASE_AUTH_DOMAIN=${_VUE_APP_FIREBASE_AUTH_DOMAIN}',
    'VUE_APP_FIREBASE_DATABASE_URL=${_VUE_APP_FIREBASE_DATABASE_URL}',
    'VUE_APP_FIREBASE_PROJECT_ID=${_VUE_APP_FIREBASE_PROJECT_ID}',
    'VUE_APP_FIREBASE_STORAGE_BUCKET=${_VUE_APP_FIREBASE_STORAGE_BUCKET}',
    'VUE_APP_FIREBASE_MESSAGE_SENDER_ID=${_VUE_APP_FIREBASE_MESSAGE_SENDER_ID}',
    'VUE_APP_FIREBASE_APP_ID=${_VUE_APP_FIREBASE_APP_ID}'
  ]
# Deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']